# Tipo do carregador de mods - para NeoForge deve ser javafml
modLoader="javafml"

# Intervalo de versão do carregador
loaderVersion="${loader_version_range}"

# Licença do seu mod
license="${mod_license}"

# Declaração do bloco do mod
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

# Quem criou o mod
authors="${mod_authors}"

# A descrição do seu mod
description='''${mod_description}'''

# Dependência Obrigatória: NeoForge
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

# Dependência Obrigatória: Minecraft Base
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
